homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  currency: !secret currency
  country: !secret country
  unit_system: metric
  time_zone: Europe/London
  external_url: !secret external_url
  internal_url: !secret internal_url
  packages: !include_dir_named configuration/integrations/
