---
# 
# This package contains the automations and sensors relating to Github Actions CI
#

- platform: rest
  resource: https://api.github.com/repos/tiberiushunter/hassio-config/actions/runs?per_page=1
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor
    Authorization: !secret github_actions_token
  value_template: >
    {% if value_json.workflow_runs[0].status != "completed" %}
      {{ value_json.workflow_runs[0].status }}
    {% else %}
      {{ value_json.workflow_runs[0].conclusion }}
    {% endif %}
  scan_interval:
    seconds: 30
  
  name: "Github Actions Build Status"

- platform: command_line
  name: Git
  command: 'git log -1 --pretty=format:''{"commit": "%H", "abbreviated_commit": "%h", "refs": "%D", "subject": "%s", "author": { "name": "%aN", "email": "%aE", "date": "%aD"}, "commiter": { "name": "%cN", "email": "%cE", "date": "%cD" } }'''
  value_template: >
    {{ value_json.abbreviated_commit }}
  json_attributes:
    - commit
    - refs
    - subject
    - author
    - commiter
