---
# 
# This package contains the automations and sensors relating to Github Actions CI
#

- alias: Github Actions Build Starting
  trigger:
    - platform: state
      entity_id: sensor.github_actions_build_status
      to: "in_progress"
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Github Actions CI
        message: Hassio Build Started! {{ "\u231B" }}
        data:
          url: "https://github.com/tiberiushunter/hassio-config/actions"
          group: Hassio
          priority: high
          tag: ciBuild
          icon_url: "https://github.com/home-assistant/brands/blob/master/core_integrations/github/icon.png?raw=true"

- alias: Github Actions Build Failed
  trigger:
    - platform: state
      entity_id: sensor.github_actions_build_status
      to: "failure"
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Github Actions CI
        message: Hassio Build Failed! {{ "\uD83E\uDD2C" }}
        data:
          url: "https://github.com/tiberiushunter/hassio-config/actions"
          group: Hassio
          priority: high
          tag: ciBuild
          message: clear_notification
          icon_url: "https://github.com/home-assistant/brands/blob/master/core_integrations/github/icon.png?raw=true"

- alias: Github Actions Build Passed
  trigger:
    - platform: state
      entity_id: sensor.github_actions_build_status
      to: "success"
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Github Actions CI
        message: Hassio Build Passed! {{ "\uD83D\uDC4D" }}
        data:
          url: "https://github.com/tiberiushunter/hassio-config/actions"
          group: Hassio
          priority: high
          tag: ciBuild
          message: clear_notification
          icon_url: "https://github.com/home-assistant/brands/blob/master/core_integrations/github/icon.png?raw=true"
    - service: hassio.addon_start
      data:
        addon: core_git_pull

