---
# 
# Triggers a notification whenever the system boots or shuts down.
#

- alias: Hassio Startup Notification
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Hassio
        message: Back Online! {{ "\uD83E\uDD29" }}
        data:
          group: Hassio
          priority: high
          icon_url: "https://raw.githubusercontent.com/home-assistant/brands/master/core_integrations/_homeassistant/icon.png?raw=true"

- alias: Hassio Shutdown Notification
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Hassio
        message: Going Offline! {{ "\uD83D\uDE34" }}
        data:
          group: Hassio
          priority: high
          icon_url: "https://raw.githubusercontent.com/home-assistant/brands/master/core_integrations/_homeassistant/icon.png?raw=true"
