---
# 
# The ping binary sensor platform allows you to use ping to send ICMP echo requests.
#
# https://www.home-assistant.io/integrations/ping/


- platform: ping
  name: internal
  host: !secret WDC01ERX
  scan_interval: 60

- platform: ping
  name: external
  host: 1.1.1.1
  scan_interval: 60
